export const SEARCH_PEOPLE = 'SEARCH_PEOPLE';
export const SORT = 'SORT';
export const SORT_BY_PICTURE = 'SORT_BY_PICTURE';
export const GET_PEOPLE_REQUEST = 'GET_PEOPLE_REQUEST';
export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_PEOPLE_ERROR = 'GET_PEOPLE_ERROR';
export const SET_ID = 'SET_ID';